{% set name = "amqp" %}
{% set version = "5.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fcd5b3baeeb7fc19b3486ff6d10543099d40ae1f5c9196eae695d1cde1b2f784

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - vine ==5.0.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - amqp

about:
  home: https://github.com/celery/py-amqp/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Low-level AMQP client for Python (fork of amqplib)
  doc_url: https://amqp.readthedocs.io/
  dev_url: https://github.com/celery/py-amqp/

extra:
  recipe-maintainers:
    - anguslees
    - kwilcox
    - wseaton
    - frol
