{% set name = "amqp" %}
{% set version = "5.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 03e16e94f2b34c31f8bf1206d8ddd3ccaa4c315f7f6a1879b7b1210d229568c2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - vine ==5.0.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - amqp

about:
  home: https://github.com/celery/py-amqp/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Low-level AMQP client for Python (fork of amqplib)
  doc_url: https://amqp.readthedocs.io/
  dev_url: https://github.com/celery/py-amqp/

extra:
  recipe-maintainers:
    - anguslees
    - kwilcox
    - wseaton
    - frol
