{% set name = "amqp" %}
{% set version = "2.5.1" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 19a917e260178b8d410122712bac69cb3e6db010d68f6101e7307508aded5e68

build:
    noarch: python
    number: 0
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - pip
    run:
        - python
        - vine >=1.1.3

test:
    imports:
        - amqp

about:
    home: http://github.com/celery/py-amqp
    license: BSD 3-clause
    license_family: BSD
    license_file: LICENSE
    summary: Low-level AMQP client for Python (fork of amqplib)
    doc_url: https://amqp.readthedocs.io/
    dev_url: http://github.com/celery/py-amqp/

extra:
    recipe-maintainers:
        - anguslees
        - kwilcox
        - wseaton
        - frol
