{% set name = "amqp" %}
{% set version = "5.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amqp-{{ version }}.tar.gz
  sha256: 113e663106a2fb0123c9030d42bf3959b96249283ff1423ab07f5cad062d36f7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - vine >=5.0.0,<6.0.0

test:
  imports:
    - amqp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/celery/py-amqp/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Low-level AMQP client for Python (fork of amqplib)
  doc_url: https://amqp.readthedocs.io/
  dev_url: https://github.com/celery/py-amqp/

extra:
  recipe-maintainers:
    - anguslees
    - kwilcox
    - wseaton
    - frol
