{% set name = "amqp" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/amqp-{{ version }}.tar.gz
  sha256: a1ecff425ad063ad42a486c902807d1482311481c8ad95a72694b2975e75f7fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - vine >=5.0.0,<6.0.0

test:
  imports:
    - amqp
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/celery/py-amqp/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Low-level AMQP client for Python (fork of amqplib)
  doc_url: https://amqp.readthedocs.io/
  dev_url: https://github.com/celery/py-amqp/

extra:
  recipe-maintainers:
    - anguslees
    - kwilcox
    - wseaton
    - frol
